#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

echo "Did you add a real instrumental key?"
echo "If you are doing local development, did you change backends to be ./../../?"

$(npm bin)/statsd exampleConfig.js
